swagger: '2.0'
info:
  description: Server-End for Wechat Xiaochengxu
  version: 1.0.0
  title: JIAN-JIAN-se
  contact:
    email: wubw6@mail2.sysu.edu.cn
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: virtserver.swaggerhub.com
basePath: /Bowenwu1/JIAN-JIAN-se/1.0.0
tags:
  - name: users
    description: Operations available to regular users
schemes:
  - https
paths:
  /books:
    get:
      tags:
        - users
      summary: 获取书架上的所有书
      description: |
        通过某种鉴权方式，获取该用户书架上的书
      operationId: getBooks
      produces:
        - application/json
      parameters:
        - name: user_id
          in: query
          description: identity an user
          required: true
          type: string
        - name: limit
          in: query
          description: maximum number of records to return
          required: false
          type: integer
          maximum: 30
          minimum: 0
          format: int32
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
        '400':
          description: unsuccess
    post:
      tags:
        - users
      summary: 添加一本书
      description: 将一本书加到某一用户的书架上， 书籍信息通过查询接口获得
      operationId: add Book
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: book
          description: 添加书籍的信息
          required: false
          schema:
            $ref: '#/definitions/Book'
      responses:
        '201':
          description: 成功添加
        '400':
          description: 非法的输入
        '409':
          description: 已经有这本书
    delete:
      tags:
        - users
      summary: 删除一本书，并且删除该书的所有书摘
      description: 删除一本书，并且删除该书的所有书摘1
      operationId: delete a book
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: book
          description: 删除的书
          required: false
          schema:
            $ref: '#/definitions/Book'
      responses:
        '201':
          description: 成功删除
        '400':
          description: 错误
  /sentence:
    get:
      tags:
        - users
      summary: 获取某一本书的所有书摘
      description: 获取某一本书的所有书摘
      operationId: get list of sentences
      produces:
        - application/json
      parameters:
        - name: isbn
          in: query
          description: 书籍唯一标示
          required: true
          type: string
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/Sentence'
        '400':
          description: 失败
        '401':
          description: 非法请求
    post:
      tags:
        - users
      summary: 给某一用户的某一本书增加一书摘
      description: 给某一用户的某一本书增加一书摘
      operationId: add sentence
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          description: 书籍唯一标示
          required: false
          schema:
            $ref: '#/definitions/AddSentence'
      responses:
        '201':
          description: 成功添加
  /square_sentences:
    get:
      tags:
        - users
      summary: 获得广场上的书摘
      parameters: []
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/SharedSentencesItem'
        '400':
          description: 失败
        '401':
          description: 非法请求
    post:
      tags:
        - users
      summary: 分享书摘
      parameters:
        - in: body
          name: sentence
          description: 要分享的书摘
          required: false
          schema:
            $ref: '#/definitions/SharedSentencesItem'
      responses:
        '201':
          description: 成功添加
          schema:
            $ref: '#/definitions/SharedSentencesItem'
        '400':
          description: 失败
        '401':
          description: 非法请求
    put:
      tags:
        - users
      summary: 用于点赞对应的句子
      description: 用于点赞对应的句子
      parameters:
        - in: body
          name: whetherZan
          description: 0 - 取消赞  1 - 赞
          required: true
          type: false
  '/book_info:{isbn}':
    get:
      tags:
        - users
      summary: 根据ISBN码获取书籍的相关信息， 此接口不需要登陆
      responses:
        '200':
          description: 成功
          schema:
            $ref: '#/definitions/book_info'
        '400':
          description: 对不起，找不到此书
definitions:
  Book:
    type: object
    required:
      - title
      - isbn
      - book_id
      - title_page_url
      - sample_sentences
    properties:
      isbn:
        type: string
        example: '97809781'
      book_id:
        type: int
        example: 123456789
      title:
        type: string
        example: Computer NetWorking(Fourth Edition)
      title_page_url:
        type: string
        example: >-
          https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2095073156,2011499721&fm=27&gp=0.jpg
        description: the Image URL
      sample_sentences:
        type: array
        example: '[''dfsdf'', ''sdfsdfsdf'', ''sdfsdf'']'
        description: 每本书的前几条书摘
    example:
      title_page_url: >-
        https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2095073156,2011499721&fm=27&gp=0.jpg
      isbn: '97809781'
      title: Computer NetWorking(Fourth Edition)
  Sentence:
    type: object
    required:
      - sentence_id
      - add_time
      - isbn
      - sentence
    properties:
      sentence_id:
        type: int32
        example: 123456789
      isbn:
        type: string
        example: '97809781'
      sentence:
        type: string
        example: 生活就像海洋，只有意志坚定的人才能到达彼岸
      add_time:
        type: string
        example: '2018-02-28'
    example:
      sentence: 生活就像海洋，只有意志坚定的人才能到达彼岸
      isbn: '97809781'
      add_time: '2018-02-28'
  AddSentence:
    type: object
    required:
      - isbn
      - sentence
    properties:
      isbn:
        type: string
        example: '97809781'
      sentence:
        type: string
        example: 生活就像海洋，只有意志坚定的人才能到达彼岸
    example:
      sentence: 生活就像海洋，只有意志坚定的人才能到达彼岸
      isbn: '97809781'
  SharedSentencesItem:
    type: object
    required:
      - sentences
      - share_comment
      - share_time
      - sharer_id
    properties:
      sentences:
        type: array
        example:
          Sentence1: null
          Sentence2: null
          Sentence3: null
        items:
          $ref: '#/definitions/Sentence'
      share_time:
        type: string
        example: '2018-02-28'
      share_comment:
        type: string
        example: 这是我喜欢的句子
      sharer_id:
        type: string
        example: ...?
    example:
      share_time: '2018-02-28'
      sentences:
        Sentence1: null
        Sentence2: null
        Sentence3: null
      sharer_id: ...?
      share_comment: 这是我喜欢的句子
  book_info:
    type: object
    required:
      - title
      - isbn
      - title_page_url
    properties:
      title:
        type: string
        example: Computer NetWorking(Fourth Edition)
      isbn:
        type: string
        example: '97809781'
      title_page_url:
        type: string
        example: >-
          https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2095073156,2011499721&fm=27&gp=0.jpg