-- MySQL Script generated by MySQL Workbench
-- Fri Mar  9 10:34:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JIAN-JIAN
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `JIAN-JIAN` ;

-- -----------------------------------------------------
-- Schema JIAN-JIAN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JIAN-JIAN` DEFAULT CHARACTER SET utf8 ;
USE `JIAN-JIAN` ;

-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`user` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nick_name` VARCHAR(128) NULL,
  `avator_url` TEXT(65536) NULL,
  `open_id` VARCHAR(32) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `open_id_UNIQUE` (`open_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`book_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`book_info` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`book_info` (
  `isbn` VARCHAR(13) NOT NULL,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `title_page_image` TEXT(65536) NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`book` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_book_user_idx` (`user_id` ASC),
  INDEX `fk_book_book_info1_idx` (`isbn` ASC),
  CONSTRAINT `fk_book_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `JIAN-JIAN`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_book_info1`
    FOREIGN KEY (`isbn`)
    REFERENCES `JIAN-JIAN`.`book_info` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`sentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`sentence` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`sentence` (
  `sentence_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `content` VARCHAR(150) NULL,
  `add_time` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`sentence_id`),
  INDEX `fk_sentence_book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_sentence_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `JIAN-JIAN`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`square`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`square` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`square` (
  `square_id` INT NOT NULL AUTO_INCREMENT,
  `author_user_id` INT NOT NULL,
  `sentence_id1` INT NOT NULL,
  `sentence_id2` INT NULL,
  `sentence_id3` INT NULL,
  `sentence_num` INT NULL,
  ` thoughts` VARCHAR(150) NULL,
  `add_time` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`square_id`),
  INDEX `fk_square_user1_idx` (`author_user_id` ASC),
  INDEX `fk_square_sentence1_idx` (`sentence_id1` ASC),
  INDEX `fk_square_sentence2_idx` (`sentence_id2` ASC),
  INDEX `fk_square_sentence3_idx` (`sentence_id3` ASC),
  CONSTRAINT `fk_square_user1`
    FOREIGN KEY (`author_user_id`)
    REFERENCES `JIAN-JIAN`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_square_sentence1`
    FOREIGN KEY (`sentence_id1`)
    REFERENCES `JIAN-JIAN`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_square_sentence2`
    FOREIGN KEY (`sentence_id2`)
    REFERENCES `JIAN-JIAN`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_square_sentence3`
    FOREIGN KEY (`sentence_id3`)
    REFERENCES `JIAN-JIAN`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`zan_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`zan_record` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`zan_record` (
  `zan_id` INT NOT NULL,
  `square_id` INT NOT NULL,
  `zan_user_id` INT NOT NULL,
  `add_time` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`zan_id`),
  INDEX `fk_zan_record_square1_idx` (`square_id` ASC),
  INDEX `fk_zan_record_user1_idx` (`zan_user_id` ASC),
  CONSTRAINT `fk_zan_record_square1`
    FOREIGN KEY (`square_id`)
    REFERENCES `JIAN-JIAN`.`square` (`square_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zan_record_user1`
    FOREIGN KEY (`zan_user_id`)
    REFERENCES `JIAN-JIAN`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JIAN-JIAN`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JIAN-JIAN`.`comment` ;

CREATE TABLE IF NOT EXISTS `JIAN-JIAN`.`comment` (
  `comment_id` INT NOT NULL,
  `square_square_id` INT NOT NULL,
  `comment_user_id` INT NOT NULL,
  `content` VARCHAR(140) NULL,
  `add_time` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_square1_idx` (`square_square_id` ASC),
  INDEX `fk_comment_user1_idx` (`comment_user_id` ASC),
  CONSTRAINT `fk_comment_square1`
    FOREIGN KEY (`square_square_id`)
    REFERENCES `JIAN-JIAN`.`square` (`square_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`comment_user_id`)
    REFERENCES `JIAN-JIAN`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
